### ISSUE TITLE
👁の幅がおかしい

### ISSUE THREAD

**Issue by Khronos31** [jiro4989/textimg#120]
go-runewidth v0.0.7以降に存在するバグです。https://github.com/jiro4989/textimg/blob/master/scripts/width/main.go を使って調べると👁の幅が1となっている事がわかります。

**Comment by jiro4989** [comment]
あやー、vendor ディレクトリ消した関係で依存ライブラリのバージョンが変わったからか

**Comment by jiro4989** [comment]
0.0.6 に戻してみるかね

**Comment by jiro4989** [comment]
0.0.6 に戻してみたらズレなくなった

**Comment by jiro4989** [comment]
まぁ最新版にこだわる理由もないし、古いバージョンで1年以上使われて問題なかったわけだし、
古いバージョンに戻しますかね

**Comment by Khronos31** [comment]
バグを見つけてしまった以上、修正してPRを出す予定ではあります。
textimgに関しては、古いバージョンで問題ないのであればその対処で良いかと思います。

**Comment by jiro4989** [comment]
一旦は古いバージョンに戻して固定しました。折を見て最新にあげときます

**Comment by jiro4989** [comment]
修正終わったはずなのでクローズします
