### ISSUE TITLE
ANSI/Truecolorの挙動について

### ISSUE THREAD

**Issue by blacknon** [jiro4989/textimg#127]
以下のコマンドを実行したところ、Color codeの解釈の問題かターミナルの表示と異なりずれてしまった(´・ω・｀)

```bash
cat /ShellGeiData/vol.54/nejineji.txt | sed 's/　/💩/g' | lolcat -f --freq=0.5 | sed -r 's/\x1B\[38;5;[0-9]{1,3}m([^💩]{1})\x1B\[39m/\1/g;s/\x1B\[38;5;[0-9]{1,3}m\x1B\[39m//g' | textimg -sF 50 -z #シェル芸
```

![スクリーンショット_2021-06-26_17-57-14](https://user-images.githubusercontent.com/11777090/123508225-019fd080-d6a9-11eb-8591-6005db3c75d0.png)
![t](https://user-images.githubusercontent.com/11777090/123508236-154b3700-d6a9-11eb-8b93-f3e38570832f.png)

**Comment by jiro4989** [comment]
僕のUbuntu環境ではそもそも `sed` に失敗してるように見えます

![image](https://user-images.githubusercontent.com/13825004/123883138-58482b80-d983-11eb-96dd-5fd88ec2b2c1.png)

**Comment by jiro4989** [comment]
@blacknon  あとtextimgはANSIエスケープシーケンスの 39 番 (default foreground color) には対応していません

**Comment by blacknon** [comment]
あら…
私の環境(manjaro/macos)だと両方ともうまく動作していたので、動作は大丈夫なのかなと思っていました 😅 

エスケープシーケンスの39に対応していないのは把握してなかったですね（多分、ターミナルカラーのデフォルトって概念があまり無いので、言われてみればそりゃそうだ感）

ということは、lolcatの結果を改変する方式の場合は、エスケープシーケンスの置換にちょっと工夫が必要ってことですね 🤔 
把握しました、ありがとうございます〜 🙏

**Comment by blacknon** [comment]
(Closeし忘れた…)
