### ISSUE TITLE
[feature request] Option to print out raw rgb24 bytes to stdout

### ISSUE THREAD

**Issue by Tanishq-Banyal** [jiro4989/textimg#128]
Please add an option to print out raw rgb24 bytes to stdout. This will be useful, for example, we can pipe output of textimg to ffmpeg to create a MP4 video.

BTW, how does textimg choose frames when creating gifs ?

**Comment by jiro4989** [comment]
> BTW, how does textimg choose frames when creating gifs ?

Use `-d` option for setting animation delay time.

```bash
⟩ textimg -h | grep "\-d"
  -d, --delay int                 animation delay time (default 20)
```

**Comment by jiro4989** [comment]
> Please add an option to print out raw rgb24 bytes to stdout. This will be useful, for example, we can pipe output of textimg to ffmpeg to create a MP4 video.

Is this not enough?

![image](https://user-images.githubusercontent.com/13825004/141607863-3b597d26-7ddf-4085-8280-cd7eadf78848.png)

**Comment by Tanishq-Banyal** [comment]
> Is this not enough?
> 
> ![image](https://user-images.githubusercontent.com/13825004/141607863-3b597d26-7ddf-4085-8280-cd7eadf78848.png)

That's a PNG, and needs additional decoding to get the pixels.

I am asking to just dump the raw pixels (without encoding them as a PNG). Because encoding as png is useless (wastage to resources) if need to decode them again to get the pixel array

**Comment by jiro4989** [comment]
Try this.

```bash
git clone https://github.com/jiro4989/textimg
cd textimg
git checkout "feature/#128/rawpix"
go install

textimg -r test | cat
textimg -r test | {your ffmpeg command}
```

**Comment by Tanishq-Banyal** [comment]
ok thanks, but how do I determine the dimensions of outputted pixel stream (given that I already know maximum characters in one line)? are there any flags for specific resolution ?

**Comment by jiro4989** [comment]
Try this.

```bash
git clone https://github.com/jiro4989/textimg
cd textimg
git checkout "feature/#128/rawpix"
go install

# 100 pixel width
textimg -r test --resize-width 100 | cat
textimg -r test --resize-width 100 | {your ffmpeg command}
```
