### ISSUE TITLE
自動改行機能 Automatic line breaks

### ISSUE THREAD

**Issue by ed9w2in6** [jiro4989/textimg#180]
指定した文字数で改行する機能が欲しいのですが、現在、一行の文字数がで65565を超えるとbufio.Scanner: token too longというエラーになります。
そして、大体2000文字を超えると画像がほぼ読めないので、約150文字で改行するのをデフォルトにすればいいかと思います。

I believe a feature of automatically inserting line breaks would be beneficial.  Currently, if a line has over 65565 characters, go will complain about "bufio.Scanner: token too long".  Moreover, lines are almost unreadable from 2000 characters and on, so setting the default of to 150 should be great as a start I reckon.

**Comment by ed9w2in6** [comment]
Sorry for throwing this out, I don't know go so I haven't really looked into the codes.

**Comment by jiro4989** [comment]
`textimg` only converts text to image.
Text formatting is not a role of `textimg`.
Please format with other commands.

```bash
cat foobar.txt | <other commands> | textimg -o out.png
```

**Comment by ed9w2in6** [comment]
I guess you are right on this.
Sorry I am using too much `Emacs` 😂.
Let me close this issue.
