### ISSUE TITLE
Text not converting to image correctly within docker

### ISSUE THREAD

**Issue by dtbaker** [jiro4989/textimg#206]
## Describe the bug

It seems some characters are missing during the conversion. 

## To Reproduce

Build docker image locally on Raspberry Pi:

```
git clone https://github.com/jiro4989/textimg.git
cd textimg/
docker build . -t textimg
```

Install tmux and bpytop tools
```
sudo apt install tmux bpytop
```

Capture bpytop output into `bpytop.txt` file:
```
tmux new -dstelemetry 'bpytop'
tmux capture-pane -e -J -p -t telemetry > bpytop.txt
tmux kill-session
```

Use docker to convert output to image:
```
docker run -v $(pwd):/images --entrypoint "/bin/sh" -it textimg
# cat images/bpytop.txt | /usr/local/bin/textimg -o images/bpytop.jpg
```

## Screenshots or Logs

![image](https://user-images.githubusercontent.com/543073/221388601-1b747e42-1d76-4de2-8cda-a940348eee57.png)

## Environment (please complete the following information)

- OS: Raspberry Pi OS
- 

## Additional context

```
$ cat bpytop.txt 
┌─┤¹cpu├──┤Menu├┤mode:full├────────┤12:09:30├─────────────────────┤+ 2000ms -├─┐
│                                    ┌──────────────────────────────┤600 Mhz├┐ │
│                                    │CPU ■■■■■■■■■■■■■■■■■■   0% ⣶⣶⣶⣶⣶  58°C│ │
│       ⡀      ⢠⡀  ⡀                 │C1  ⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀  0%│C3  ⡀⡀⣀⡀⣀⡀⣀⡀⣀⡀⣀  1%│ │
│       ⠁      ⠘⠁  ⠁                 │C2  ⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀  0%│C4  ⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀  0%│ │
│                                    │                    LAV: 0.11 0.22 0.3 │ │
│ up 0:40                            └───────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────────┘
┌─┤²mem├┤graph├───┬─┤dis┤io├┤swap├─┐┌─┤⁴proc├┤filter├─────┤tree├┤< cpu lazy >├─┐
│ Total: 7.62 GiB ├──root───14.3─G─┤│   Pid: Program:         MemB       Cpu% ↑│
│ U ⣀⣀⣀⣀⣀⣀  402 M │ U ■■■■■ 4.03 G ││   2815 python3           34M ⣀⣀⣀⣀⣀  0.8 █│
│ A ⣿⣿⣿⣿⣿⣿ 7.23 G ├──swap───99.9─M─┤│    669 dockerd           91M ⡀⡀⡀⡀⡀  0.0  │
│ C ⣤⣤⣤⣤⣤⣤ 2.02 G │ U ■■■■■   0 By ││    582 kworker/u9:2-brc   0B ⡀⡀⡀⡀⡀  0.0  │
│ F ⣶⣶⣶⣶⣶⣶ 5.28 G ├──boot────254─M─┤│   2814 tmux: server       3M ⡀⡀⡀⡀⡀  0.0  │
├─────────────────┤ IO ⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀  ││      1 systemd           10M ⡀⡀⡀⡀⡀  0.0  │
│                 │ U ■■■■■ 30.5 M ││    531 containerd        40M ⡀⡀⡀⡀⡀  0.0  │
│                 │                ││    848 node              75M ⡀⡀⡀⡀⡀  0.0  │
└─────────────────┴────────────────┘│    671 node              79M ⡀⡀⡀⡀⡀  0.0  │
┌─┤³net├─┤auto├┤zero├┤<b wlan0 n>├─┐│    170 systemd-udevd      6M ⡀⡀⡀⡀⡀  0.0  │
│10K           ┌─┤Download├──────┐ ││    900 sshd               4M ⡀⡀⡀⡀⡀  0.1  │
│      ⢀       │▼ 293 Byte/s     │ ││    137 systemd-journald  17M ⡀⡀⡀⡀⡀  0.0  │
│           ⠈⠈⠁│▲ 398 Byte/s     │ ││    881 systemd            8M ⡀⡀⡀⡀⡀  0.0  │
│10K           └─┤Upload├────────┘ ││     70 kworker/0:1H-mmc   0B ⡀⡀⡀⡀⡀  0.0 ↓│
└──────────────────────────────────┘└─┤↑ select ↓├┤info ↲├┤Terminate├──┤0/150├─
```

Attached:

[bpytop.txt](https://github.com/jiro4989/textimg/files/10832752/bpytop.txt)

**Comment by dtbaker** [comment]
Hello,

If I add this to the `Dockerfile` and re-built, the output image gets a bit nicer:

```
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```

![bpytop3](https://user-images.githubusercontent.com/543073/221388843-4d801dca-8e4f-4f86-ab47-993763afbcbd.jpg)

but still missing a few characters

**Comment by jiro4989** [comment]
The textimg Dockerfile uses MyricaM as the font.
https://github.com/jiro4989/textimg/blob/32e541eaf37f472bb1342454fd2f383c6e066d08/Dockerfile#L31

Maybe, the character is missing because the font file does not contain that character.
Please add another fonts and overwrite the environment variable `TEXTIMG_FONT_FILE`.

**Comment by dtbaker** [comment]
Thank you for the suggestion. 

I tried: `DejaVuSansMono.ttf`
![bpytop-defavu](https://user-images.githubusercontent.com/543073/221399516-cdcad88d-3110-420a-befc-53909e07d14f.jpg)



Then `NotoMono-Regular.ttf`

![bpytop-notomono](https://user-images.githubusercontent.com/543073/221399523-7064998a-56f6-4f71-adb5-9b8fabf181bd.jpg)


And `NotoSansCJK-Regular.ttc`

![bpytop-notosans](https://user-images.githubusercontent.com/543073/221399527-be0bb4a3-ed60-4c41-994c-d47f098a284e.jpg)



And also `Hack-Regular.ttf`

![bpytop-hack](https://user-images.githubusercontent.com/543073/221399531-deee8c7d-9c49-452b-a1ad-ebd5ae3cad20.jpg)



Does the attached file work with any font you have by chance? 
[bpytop.txt](https://github.com/jiro4989/textimg/files/10832752/bpytop.txt)
 

Have you come across any other similar tools to this that I can try as well to see if they have the same problem?

Thank you very much.

**Comment by jiro4989** [comment]
> Does the attached file work with any font you have by chance?

I tried it, but the characters were missing.

> Have you come across any other similar tools to this that I can try as well to see if they have the same problem?

I have never tried other tools. ImageMagick will be a similar tool.

**Comment by jiro4989** [comment]
The missing characters (`⢠⡀`) will be Braille.
For example, it will be drawn when I use a font that contains only Braille.

![a](https://user-images.githubusercontent.com/13825004/221442063-046b8545-e6c9-4600-874c-7c45090b017f.png)

So this is a font issue.
