### ISSUE TITLE
Letter spacing

### ISSUE THREAD

**Issue by Goxore** [jiro4989/textimg#229]
Can you please add a flag for letter spacing?

**Comment by jiro4989** [comment]
Please write a specific use case

**Comment by Goxore** [comment]
JetbrainsMono's letters seem quite wide, and it looks a little weird. I think this feature would solve it.

**Comment by jiro4989** [comment]
I haven't used JetbrainsMono so I don't understand what you want to do.  
Please write your input and expected values.

**Comment by Goxore** [comment]
Ok, my apologies, my initial assumption was incorrect. Some letters are getting cut a little bit at the end, but now I see that it only happens when syntax highlighting is enabled. I thought that they just needed more space.

### bat syntax highlighting enabled
![test](https://github.com/jiro4989/textimg/assets/54540106/f1ddcdea-de19-4870-b5c3-c8947d9ceefd)

`./textimg "$(bat --color=always --style=plain --theme="gruvbox-dark" ./test.nix)" -F 120 -b 40,40,40,255 -o test.png`

### bat syntax highlighting disabled
![test](https://github.com/jiro4989/textimg/assets/54540106/ae205a20-0cfd-4933-b948-c48d2eea5c21)

`$ ./textimg "$(bat --style=plain --theme="gruvbox-dark" ./test.nix)" -F 120 -b 40,40,40,255 -o test.png`

###difference
![image](https://github.com/jiro4989/textimg/assets/54540106/929688dd-cee0-486f-9f7c-11fb5673e3c7)
![image](https://github.com/jiro4989/textimg/assets/54540106/207e717e-ffdd-4522-870f-473790b5c327)

some letters are getting cut a tiny bit at the end. Not letter spacing issue, but still an issue.

font: https://github.com/JetBrains/JetBrainsMono

### text.nix test file
```
{
  description = "example";

  inputs =
    {
      nixpkgs.url = "github:nixos/nixpkgs";
    };

  outputs = { self, nixpkgs, unstablenixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem
      (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          devShell =
            pkgs.mkShell
              {

              };
        }
      );
}
```

**Comment by jiro4989** [comment]
Ah, I see. I understood it.

**Comment by jiro4989** [comment]
In fact, letter-spacing calculations of `textimg` are very crude.  
I knew this when I first created textimg. Especially when drawing emojis.  

`texting` was originally a joke app. So I left this issue alone.

I'll see if adding a letter-spacing parameter will solve the problem.

**Comment by jiro4989** [comment]
It seems that the characters are overwritten by the background color drawing process.  
I'm working on fixing the bugs.

```bash
⟩ echo -e '\x1b[31mggg\x1b[mggg\nggg\x1b[32mggg\x1b[m\n\x1b[33mggg\x1b[mg\x1b[45mg\x1b[mg' | ./textimg -o ~/Downloads/color_ggg_2.png -F 120 -b 40,40,40,255
```

Result:

![color_ggg_2](https://github.com/jiro4989/textimg/assets/13825004/6733e6de-3d8e-43ce-8b94-eec39de7ebfd)

```bash
⟩ echo -e '\x1b[31mggg\x1b[mggg\nggg\x1b[32mggg\x1b[m\n\x1b[33mggg\x1b[mg\x1b[45mg\x1b[mg' | ./textimg -o ~/Downloads/color_ggg_2_cyan.png -F 120 -b 40,40,40,255 -b cyan
```

Result:

![color_ggg_2_cyan](https://github.com/jiro4989/textimg/assets/13825004/840e1029-0074-4156-a99e-699598fdc195)

**Comment by jiro4989** [comment]
@Goxore I was late, sorry 🙇
I fixed the issues that some letters are getting cut a tiny bit at the end.
Please use textimg version `v3.1.9` or `master` branch.
