### ISSUE TITLE
Chinese characters do not work properly

### ISSUE THREAD

**Issue by lomirus** [jiro4989/textimg#232]
## Describe the bug

Chinese characters do not work properly, display as blocks

![WX20230802-194627@2x](https://github.com/jiro4989/textimg/assets/21173956/e86597ea-d5d3-4a0b-be89-3be9c0aad432)
## To Reproduce

```bash
echo "测试" | textimg -o m.png
open m.png
```

## Expected behavior

Displays "测试"

## Environment (please complete the following information)

- OS: MacOS 13.5
- Version: 3.1.7

**Comment by jiro4989** [comment]
First of all, please check the font that it supports Chinese.

See: https://github.com/jiro4989/textimg#fonts

And, I haven't tested languages other than Japanese and English, and I have no plans to support them.
