### ISSUE TITLE
Build package for arm64

### ISSUE THREAD

**Issue by sunilsankar** [jiro4989/textimg#262]
There is no package for arm64. Can you build one

**Comment by sunilsankar** [comment]
Let me know the steps can build it

**Comment by jiro4989** [comment]
What do you mean?
I create arm64 packages, not you. Why do I need to teach you?

**Comment by sunilsankar** [comment]
What I meant was share the spec file since I have env I can build it for you . No offense pls build it on your own

**Comment by jiro4989** [comment]
@sunilsankar I added arm64 binaries. (v3.1.10)

https://github.com/jiro4989/textimg/releases/tag/v3.1.10

**Comment by sunilsankar** [comment]
Thanks it works :)
