### ISSUE TITLE
🦵(leg)の絵文字が `-szF40` 時に「？」に化ける

### ISSUE THREAD

**Issue by ykamenashi** [jiro4989/textimg#58]
* https://twitter.com/minyoruminyon/status/1160777281238786048
* https://twitter.com/ytkmns/status/1160777244303753218

**Comment by jiro4989** [comment]
どうもこの足の絵文字は文字幅1として描画されようとしているみたいでした。

絵文字の幅は全角文字と同じとして扱うようにしているのですが、
画像バッファには半角文字と同じ幅しか用意していないので
画像の描画先が存在しなくてクラッシュしています。

しかしながら、この問題は絵文字が？になる理由とは別になります。

```bash
$ docker run -v $(pwd):/images -it jiro4989/textimg -s "🦵" 2>&1

panic: png: invalid format: invalid image size: 0x22

goroutine 1 [running]:
main.writeImage(0x68c960, 0xc0000800b0, 0x0, 0xc00008c220, 0x1, 0x2, 0xff000000ffffffff, 0x64a30b, 0xd, 0xc00001c012, ...)
	/go/src/github.com/jiro4989/textimg/image.go:171 +0x1323
main.glob..func1(0x8340a0, 0xc00008c220, 0x1, 0x2)
	/go/src/github.com/jiro4989/textimg/root.go:239 +0xb79
github.com/jiro4989/textimg/vendor/github.com/spf13/cobra.(*Command).execute(0x8340a0, 0xc000084160, 0x2, 0x2, 0x8340a0, 0xc000084160)
	/go/src/github.com/jiro4989/textimg/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/jiro4989/textimg/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x8340a0, 0xc0000d6100, 0xc0000a9f88, 0x40642f)
	/go/src/github.com/jiro4989/textimg/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/jiro4989/textimg/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/jiro4989/textimg/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/jiro4989/textimg/main.go:9 +0x32
```

```bash
$ docker run -v $(pwd):/images -it jiro4989/textimg -s "🦵1" 2>&1
```

**Comment by jiro4989** [comment]
@ykamenashi 

# 結論

* `-z`オプションを適用したときにだけ発生するバグ
* Symbola_hint.ttfに起因する
* 僕の方で修正できるものではない

よって課題をクローズします

# 理由

`-z` (絵文字フォント有効化)オプションが有効のときだけ発生する事象です。
https://twitter.com/minyoruminyon/status/1161024253229068288

色のついている通常のときは、[noto-emoji/png](https://github.com/googlefonts/noto-emoji/tree/master/png/128)の画像をコードポイントで参照しています。
足の絵文字と対応しているのは、emoji_u1f9b5.png (U+1F9B5)です。
こちらの画像は存在するので描画されています。

`-z`が有効のときは、Symbola_hint.ttfフォントが適用されます。
今回の事象は、このSymbolaフォント側が足の絵文字に対応するものを用意していないことに起因することと考えます。
Symbolaフォントは外部のフォントファイルのため、修正はできそうにありません。
フォント製作者の対応を待ちしかないと思います。

以上です。

**Comment by ykamenashi** [comment]
@jiro4989 なるほど…。調査ありがとうございました。
