### ISSUE TITLE
非表示文字が豆腐で表示されてしまう

### ISSUE THREAD

**Issue by Khronos31** [jiro4989/textimg#59]

**Comment by jiro4989** [comment]
修正方針は下記。

1. Unicodeの非表示文字の一覧を調べる
2. 非表示文字飲みを削除する処理を追加する

おそらく、この豆腐が描画される現象はすべての非表示文字で起こりえます。
すべての非表示文字について網羅された情報が見つかればよいのですが、
僕がそれを見つけられなかった場合は、場当たり的な修正となることをご理解ください。

## 非表示文字の例

* [Unicode control characters - Wikipedia](https://en.wikipedia.org/wiki/Unicode_control_characters)
* [ゼロ幅スペース - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%BC%E3%83%AD%E5%B9%85%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9)

**Comment by jiro4989** [comment]
2年くらい放置してますし、良い対応方法も思いつかないのでやらないことにします。
