### ISSUE TITLE
ゼロ幅スペースの文字幅がおかしい

### ISSUE THREAD

**Issue by Khronos31** [jiro4989/textimg#60]
echo Unko|zws|textimg -o out.png
とした時、ゼロ幅スペースが豆腐で、しかも幅を持って描画されてしまいます。

**Comment by jiro4989** [comment]
[ゼロ幅スペース](https://ja.wikipedia.org/wiki/%E3%82%BC%E3%83%AD%E5%B9%85%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9)

**Comment by jiro4989** [comment]
以下の文字は入力受付時に削除する方針とします

* U+200B
* U+200C
* U+200D
* U+FEFF

**Comment by jiro4989** [comment]
@Khronos31 
修正しました。ご報告ありがとうございます
